### ISSUE TITLE
Cannot run ModelRender part

### ISSUE THREAD

**Issue by shahizat** [Junacik99/bac#2]
Hi @Junacik99,

I want to run your application, but I can not run the ModelRender part. Could you please explain in more details? Thanks in advance.

Best regards,
Shakhizat

**Comment by Junacik99** [comment]
Hello @shahizat,
I see you have already closed this issue, but could I ask you to explain what was the solution to your problem?
And I also want to ask if you used the link provided [here](http://www.stud.fit.vutbr.cz/~xtakac07/) or have downloaded the libraries and ran the script locally? In both cases the websocket server has to be already running before you try to open the ModelRender.

**Comment by shahizat** [comment]
Hi @Junacik99, thanks for your reply, sorry I just made a stupid mistake, so I was able to run it , everything is fine in your code in terms of running. Currently, i am investigating how to export a 3D model from Unity3D to gltf format. Also try to understand how to run open and close mouth commands using Animation in Three.js. I am a newbie in three.js))))

**Comment by Junacik99** [comment]
@shahizat for exporting gltf format or converting unity object to gltf i would recommend blender. To play an animation in three.js try to refer to this [link](https://threejs.org/docs/#manual/en/introduction/Animation-system). Good luck!
